const char deeds[]="******* DMC8 Project File *******\n"
"* If you read this message, you need to install the last version of Deeds! *\n"
"FVR 2\n"
"DMC 1\n"
"ROM 0\n"
"RAM 0\n"
"POH 7\n"
"POG 6\n"
"POF 5\n"
"POE 4\n"
"POD 3\n"
"POC 2\n"
"POB 1\n"
"POA 0\n"
"PIH 7\n"
"PIG 6\n"
"PIF 5\n"
"PIE 4\n"
"PID 3\n"
"PIC 2\n"
"PIB 1\n"
"PIA 0\n"
"******* DMC8 Project File *******\n"
"	ISET D8080";

